name: Comprobando feature realizada para enviar a develop
on:
  push:
    branches:
      - feature**

jobs:
  pruebas:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'MERGE') }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Instalación de paquetes
      run: npm install
    - name: Compilar la aplicación
      run: npm run ng build --configuration=production
    - name: Ejecutar pruebas
      run: npm run ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
    - name: Merge ${{ github.ref }} -> develop
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop
        commit-message: "INTEGRACION de funcionalidad desde ${{ github.ref }}"